# Generated by Django 4.2.4 on 2023-08-25 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols', models.IntegerField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
                ('advertencias', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('defesas', models.IntegerField(default=0)),
                ('golsSofridos', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
