# Generated by Django 4.2.6 on 2023-10-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='custo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
