# Generated by Django 4.2.6 on 2023-10-08 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('lineups', '0002_lineup_round_lineup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('titular', 'Titular'), ('goleiro', 'Goleiro'), ('reserva', 'Reserva')], max_length=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineups.lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
        ),
    ]
