# Generated by Django 4.2.6 on 2023-10-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerInLineup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinlineup',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
