# Generated by Django 4.2.6 on 2023-10-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Round',
        ),
    ]
