# Generated by Django 4.2.6 on 2023-10-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_rename_players_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='nome',
        ),
    ]
